import com.android.build.api.dsl.androidLibrary
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.util.Base64

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
}

val generatedSourceDir = layout.buildDirectory.dir("generated/p2p/kotlin")
val assetsSourceDir = layout.projectDirectory.dir("src/assets")

val generateAssetsTask = tasks.register("generateP2PAssets") {
    description = "Encodes P2P assets (JS/HTML) into a Kotlin object"
    group = "build"

    val inputDir = assetsSourceDir
    val outputDir = generatedSourceDir

    inputs.dir(inputDir)
    outputs.dir(outputDir)

    doLast {
        val folder = inputDir.asFile
        if (!folder.exists()) throw GradleException("Asset folder missing: ${folder.absolutePath}")

        val jsFile = folder.listFiles()?.firstOrNull { it.name.endsWith(".js") }
            ?: throw GradleException("No .js file found in ${folder.absolutePath}")

        val htmlFile = folder.resolve("index.html")
        if (!htmlFile.exists()) throw GradleException("index.html missing")

        val indexHtmlB64 = Base64.getEncoder().encodeToString(htmlFile.readBytes())
        val coreJsB64 = Base64.getEncoder().encodeToString(jsFile.readBytes())

        fun chunkData(data: String): String {
            return data.chunked(60000).joinToString(",\n        ") { "\"$it\"" }
        }

        val outputFile = outputDir.get().asFile.resolve("com/novage/p2pml/shared/generated/P2PAssets.kt")
        outputFile.parentFile.mkdirs()
        
        outputFile.writeText("""
            package com.novage.p2pml.shared.generated
            
            // AUTOMATICALLY GENERATED by :shared:generateP2PAssets.
            
            internal object P2PAssets {
                const val JS_FILENAME = "${jsFile.name}"

                // HTML is usually small, but let's chunk it to be safe/consistent
                private val HTML_CHUNKS = listOf(
                    ${chunkData(indexHtmlB64)}
                )
                
                // JS is >65KB, so this chunking prevents the "UTF8 string too large" error
                private val JS_CHUNKS = listOf(
                    ${chunkData(coreJsB64)}
                )

                // Public accessors that join the chunks at runtime
                val INDEX_HTML_BASE64: String get() = HTML_CHUNKS.joinToString("")
                val CORE_JS_BASE64: String get() = JS_CHUNKS.joinToString("")
            }
        """.trimIndent())
    }
}

kotlin {
    androidLibrary {
        namespace = "com.novage.p2pml.shared"
        compileSdk = libs.versions.android.compile.sdk.get().toInt()
        minSdk = libs.versions.android.min.sdk.get().toInt()

        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(JvmTarget.JVM_11)
                }
            }
        }
    }

    listOf(iosX64(), iosArm64(), iosSimulatorArm64()).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedSourceDir)

            dependencies {
                implementation(kotlin("stdlib"))
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.ktor.utils)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.server.core)
                implementation(libs.ktor.server.cio)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.server.cors)
            }
        }

        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.slf4j.simple)
            compileOnly(libs.androidx.media3.exoplayer)
            compileOnly(libs.androidx.media3.exoplayer.hls)
        }

        iosMain.dependencies { implementation(libs.ktor.client.darwin) }
    }
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(generateAssetsTask)
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinNativeCompile>().configureEach {
    dependsOn(generateAssetsTask)
}

tasks.matching { it.name == "prepareKotlinIdeaImport" }.configureEach {
    dependsOn(generateAssetsTask)
}