import java.util.Base64
import org.jetbrains.kotlin.gradle.dsl.JvmDefaultMode
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.apple.XCFramework

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.skie)
    id("buildlogic.quality")
    `maven-publish`
}

group = providers.gradleProperty("GROUP").get()
version = providers.gradleProperty("VERSION_NAME").get()

skie {
    features {
        group {
            co.touchlab.skie.configuration.SealedInterop.Enabled(false)
        }
    }
}

val generatedSourceDir = layout.buildDirectory.dir("generated/p2p/kotlin")
val assetsSourceDir = layout.projectDirectory.dir("src/assets")

val generateAssetsTask =
    tasks.register("generateP2PAssets") {
        description = "Encodes P2P Engine assets into a Kotlin object"
        group = "build"

        val inputDir = assetsSourceDir
        val outputDir = generatedSourceDir

        inputs.dir(inputDir)
        outputs.dir(outputDir)

        doLast {
            val folder = inputDir.asFile
            if (!folder.exists()) throw GradleException("Asset folder missing: ${folder.absolutePath}")

            val jsFile =
                folder.listFiles()?.firstOrNull { it.name.endsWith(".js") }
                    ?: throw GradleException("No .js file found in ${folder.absolutePath}")

            val htmlFile =
                folder.listFiles()?.firstOrNull { it.name.endsWith(".html") }
                    ?: throw GradleException("No .html file found in ${folder.absolutePath}")

            val indexHtmlB64 = Base64.getEncoder().encodeToString(htmlFile.readBytes())
            val coreJsB64 = Base64.getEncoder().encodeToString(jsFile.readBytes())

            fun chunkData(data: String): String = data.chunked(60000).joinToString(",\n        ") { "\"$it\"" }

            val outputFile = outputDir.get().asFile.resolve("com/novage/p2pml/generated/P2PAssets.kt")
            outputFile.parentFile.mkdirs()

            outputFile.writeText(
                """
                package com.novage.p2pml.generated
                
                import kotlin.io.encoding.Base64
                
                // AUTOMATICALLY GENERATED by :p2pml:generateP2PAssets.
                
                internal object P2PAssets {
                    const val JS_FILENAME = "${jsFile.name}"
                    const val HTML_FILENAME = "${htmlFile.name}"
                    
                    private val HTML_CHUNKS = listOf(
                        ${chunkData(indexHtmlB64)}
                    )
                    
                    private val JS_CHUNKS = listOf(
                        ${chunkData(coreJsB64)}
                    )
 
                    val INDEX_HTML_BYTES: ByteArray by lazy {
                        Base64.decode(HTML_CHUNKS.joinToString(""))
                    }
                    val CORE_JS_BYTES: ByteArray by lazy {
                        Base64.decode(JS_CHUNKS.joinToString(""))
                    }
                }
                """.trimIndent()
            )
        }
    }

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())

    android {
        namespace = "com.novage.p2pml"
        compileSdk =
            libs.versions.android.compile.sdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.min.sdk
                .get()
                .toInt()

        optimization {
            consumerKeepRules.file("consumer-rules.pro")
            consumerKeepRules.publish = true
        }

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
            jvmDefault.set(JvmDefaultMode.NO_COMPATIBILITY)
        }

        withHostTest {
            // android.util.Log is a throwing stub on the JVM; logging at WARN+ is on by default
            isReturnDefaultValues = true
        }
    }

    val xcframework = XCFramework("P2PML")

    listOf(iosX64(), iosArm64(), iosSimulatorArm64()).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "P2PML"
            isStatic = true
            // Without this the bundle ID defaults to the bundle name ("P2PML"), which the
            // linker warns about on every build and ships in the framework's Info.plist.
            binaryOption("bundleId", "com.novage.p2pml")
            xcframework.add(this)
        }
    }

    sourceSets {
        commonMain {
            // Carries the task dependency: every compilation that consumes this source dir
            // runs generateP2PAssets first, with no manual dependsOn wiring.
            kotlin.srcDir(generateAssetsTask)

            dependencies {
                implementation(kotlin("stdlib"))
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.ktor.utils)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.ktor.server.core)
                implementation(libs.ktor.server.cio)
                implementation(libs.ktor.client.core)
                implementation(libs.ktor.server.cors)
            }
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
            }
        }

        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            compileOnly(libs.androidx.media3.exoplayer)
        }

        iosMain.dependencies { implementation(libs.ktor.client.darwin) }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("p2pml")
            description.set(
                "Kotlin Multiplatform SDK that adds peer-to-peer segment delivery to native HLS " +
                    "playback on Android and iOS."
            )
            url.set("https://github.com/DimaDemchenko/p2pml-kmp")

            licenses {
                license {
                    name.set("The Apache License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }

            developers {
                developer {
                    id.set("DimaDemchenko")
                    name.set("Dmytro Demchenko")
                }
            }

            scm {
                url.set("https://github.com/DimaDemchenko/p2pml-kmp")
                connection.set("scm:git:https://github.com/DimaDemchenko/p2pml-kmp.git")
                developerConnection.set("scm:git:ssh://git@github.com/DimaDemchenko/p2pml-kmp.git")
            }
        }
    }
}
